name: test_regression_model
channels:
  - conda-forge
dependencies:
  - pandas
  - pip
  - mlflow
  - scikit-learn
  - pip:
      - wandb==0.10.31
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
